#!/usr/bin/env bash
score1_1=0
score1_2=0
score2_1=0
score2_2=0
score2_3=0
score2_4=0
score2_5=0
score2_6=0
score_hidden_functional=0
score1_1all=39
score1_2all=21
score2_1all=4
score2_2all=5
score2_3all=5
score2_4all=40
score2_5all=26
score2_6all=11
score_hidden_functional_all=39
pwdin=test/test/testcase
pwdout=test/IR_level_optimize_test_output
rm -rf ${pwdout}/hidden_functional/*
rm -rf ${pwdout}/level1-1/*
rm -rf ${pwdout}/level1-2/*
rm -rf ${pwdout}/level2-1/*
rm -rf ${pwdout}/level2-2/*
rm -rf ${pwdout}/level2-3/*
rm -rf ${pwdout}/level2-4/*
rm -rf ${pwdout}/level2-5/*
rm -rf ${pwdout}/level2-6/*
for file in ${pwdin}/level1-1/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/level1-1/${var##*/}.ll -O1
    clang ${pwdout}/level1-1/${var##*/}.ll -c -o ${pwdout}/level1-1/${var##*/}.o -w
    clang -static ${pwdout}/level1-1/${var##*/}.o lib/libsysy_x86.a
    rm -rf ${pwdout}/level1-1/${var##*/}.o
    mv a.out ${pwdout}/level1-1/${var##*/}
    if [ -f "${pwdin}/level1-1/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/level1-1/${var##*/} < ${pwdin}/level1-1/${var##*/}.in > ./${pwdout}/level1-1/${var##*/}.out
        echo $? >> ${pwdout}/level1-1/${var##*/}.out
    else
        timeout 10 ./${pwdout}/level1-1/${var##*/} > ./${pwdout}/level1-1/${var##*/}.out
        echo $? >> ${pwdout}/level1-1/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/level1-1/${var##*/}.out ${pwdout}/level1-1/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" level1-1 ${var##*/}
        score1_1=`expr ${score1_1} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on level1-1 ${var##*/}
    fi
    rm ${pwdout}/level1-1/${var##*/}
done
for file in ${pwdin}/level1-2/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/level1-2/${var##*/}.ll -O1
    clang ${pwdout}/level1-2/${var##*/}.ll -c -o ${pwdout}/level1-2/${var##*/}.o -w
    clang -static ${pwdout}/level1-2/${var##*/}.o lib/libsysy_x86.a 
    rm -rf ${pwdout}/level1-2/${var##*/}.o
    mv a.out ${pwdout}/level1-2/${var##*/}
    if [ -f "${pwdin}/level1-2/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/level1-2/${var##*/} < ${pwdin}/level1-2/${var##*/}.in > ./${pwdout}/level1-2/${var##*/}.out
        echo $? >> ${pwdout}/level1-2/${var##*/}.out
    else
        timeout 10 ./${pwdout}/level1-2/${var##*/} > ./${pwdout}/level1-2/${var##*/}.out
        echo $? >> ${pwdout}/level1-2/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/level1-2/${var##*/}.out ${pwdout}/level1-2/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" level1-2 ${var##*/}
        score1_2=`expr ${score1_2} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on level1-2 ${var##*/}
    fi
    rm ${pwdout}/level1-2/${var##*/}
done
for file in ${pwdin}/level2-1/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/level2-1/${var##*/}.ll -O1
    clang ${pwdout}/level2-1/${var##*/}.ll -c -o ${pwdout}/level2-1/${var##*/}.o -w
    clang -static ${pwdout}/level2-1/${var##*/}.o lib/libsysy_x86.a
    rm -rf ${pwdout}/level2-1/${var##*/}.o
    mv a.out ${pwdout}/level2-1/${var##*/}
    if [ -f "${pwdin}/level2-1/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/level2-1/${var##*/} < ${pwdin}/level2-1/${var##*/}.in > ./${pwdout}/level2-1/${var##*/}.out
        echo $? >> ${pwdout}/level2-1/${var##*/}.out
    else
        timeout 10 ./${pwdout}/level2-1/${var##*/} > ./${pwdout}/level2-1/${var##*/}.out
        echo $? >> ${pwdout}/level2-1/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/level2-1/${var##*/}.out ${pwdout}/level2-1/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" level2-1 ${var##*/}
        score2_1=`expr ${score2_1} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on level2-1 ${var##*/}
    fi
    rm ${pwdout}/level2-1/${var##*/}
done
for file in ${pwdin}/level2-2/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/level2-2/${var##*/}.ll -O1
    clang ${pwdout}/level2-2/${var##*/}.ll -c -o ${pwdout}/level2-2/${var##*/}.o -w
    clang -static ${pwdout}/level2-2/${var##*/}.o lib/libsysy_x86.a
    rm -rf ${pwdout}/level2-2/${var##*/}.o
    mv a.out ${pwdout}/level2-2/${var##*/}
    if [ -f "${pwdin}/level2-2/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/level2-2/${var##*/} < ${pwdin}/level2-2/${var##*/}.in > ./${pwdout}/level2-2/${var##*/}.out
        echo $? >> ${pwdout}/level2-2/${var##*/}.out
    else
        timeout 10 ./${pwdout}/level2-2/${var##*/} > ./${pwdout}/level2-2/${var##*/}.out
        echo $? >> ${pwdout}/level2-2/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/level2-2/${var##*/}.out ${pwdout}/level2-2/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" level2-2 ${var##*/}
        score2_2=`expr ${score2_2} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on level2-2 ${var##*/}
    fi
    rm ${pwdout}/level2-2/${var##*/}
done
for file in ${pwdin}/level2-3/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/level2-3/${var##*/}.ll -O1
    clang ${pwdout}/level2-3/${var##*/}.ll -c -o ${pwdout}/level2-3/${var##*/}.o -w
    clang -static ${pwdout}/level2-3/${var##*/}.o lib/libsysy_x86.a
    rm -rf ${pwdout}/level2-3/${var##*/}.o
    mv a.out ${pwdout}/level2-3/${var##*/}
    if [ -f "${pwdin}/level2-3/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/level2-3/${var##*/} < ${pwdin}/level2-3/${var##*/}.in > ./${pwdout}/level2-3/${var##*/}.out
        echo $? >> ${pwdout}/level2-3/${var##*/}.out
    else
        timeout 10 ./${pwdout}/level2-3/${var##*/} > ./${pwdout}/level2-3/${var##*/}.out
        echo $? >> ${pwdout}/level2-3/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/level2-3/${var##*/}.out ${pwdout}/level2-3/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" level2-3 ${var##*/}
        score2_3=`expr ${score2_3} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on level2-3 ${var##*/}
    fi
    rm ${pwdout}/level2-3/${var##*/}
done
for file in ${pwdin}/level2-4/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/level2-4/${var##*/}.ll -O1
    clang ${pwdout}/level2-4/${var##*/}.ll -c -o ${pwdout}/level2-4/${var##*/}.o -w
    clang -static ${pwdout}/level2-4/${var##*/}.o lib/libsysy_x86.a
    rm -rf ${pwdout}/level2-4/${var##*/}.o
    mv a.out ${pwdout}/level2-4/${var##*/}
    if [ -f "${pwdin}/level2-4/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/level2-4/${var##*/} < ${pwdin}/level2-4/${var##*/}.in > ./${pwdout}/level2-4/${var##*/}.out
        echo $? >> ${pwdout}/level2-4/${var##*/}.out
    else
        timeout 10 ./${pwdout}/level2-4/${var##*/} > ./${pwdout}/level2-4/${var##*/}.out
        echo $? >> ${pwdout}/level2-4/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/level2-4/${var##*/}.out ${pwdout}/level2-4/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" level2-4 ${var##*/}
        score2_4=`expr ${score2_4} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on level2-4 ${var##*/}
    fi
    rm ${pwdout}/level2-4/${var##*/}
done
for file in ${pwdin}/level2-5/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/level2-5/${var##*/}.ll -O1
    clang ${pwdout}/level2-5/${var##*/}.ll -c -o ${pwdout}/level2-5/${var##*/}.o -w
    clang -static ${pwdout}/level2-5/${var##*/}.o lib/libsysy_x86.a
    rm -rf ${pwdout}/level2-5/${var##*/}.o
    mv a.out ${pwdout}/level2-5/${var##*/}
    if [ -f "${pwdin}/level2-5/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/level2-5/${var##*/} < ${pwdin}/level2-5/${var##*/}.in > ./${pwdout}/level2-5/${var##*/}.out
        echo $? >> ${pwdout}/level2-5/${var##*/}.out
    else
        timeout 10 ./${pwdout}/level2-5/${var##*/} > ./${pwdout}/level2-5/${var##*/}.out
        echo $? >> ${pwdout}/level2-5/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/level2-5/${var##*/}.out ${pwdout}/level2-5/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" level2-5 ${var##*/}
        score2_5=`expr ${score2_5} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on level2-5 ${var##*/}
    fi
    rm ${pwdout}/level2-5/${var##*/}
done
for file in ${pwdin}/level2-6/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/level2-6/${var##*/}.ll -O1
    clang ${pwdout}/level2-6/${var##*/}.ll -c -o ${pwdout}/level2-6/${var##*/}.o -w
    clang -static ${pwdout}/level2-6/${var##*/}.o lib/libsysy_x86.a
    rm -rf ${pwdout}/level2-6/${var##*/}.o
    mv a.out ${pwdout}/level2-6/${var##*/}
    if [ -f "${pwdin}/level2-6/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/level2-6/${var##*/} < ${pwdin}/level2-6/${var##*/}.in > ./${pwdout}/level2-6/${var##*/}.out
        echo $? >> ${pwdout}/level2-6/${var##*/}.out
    else
        timeout 10 ./${pwdout}/level2-6/${var##*/} > ./${pwdout}/level2-6/${var##*/}.out
        echo $? >> ${pwdout}/level2-6/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/level2-6/${var##*/}.out ${pwdout}/level2-6/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" level2-6 ${var##*/}
        score2_6=`expr ${score2_6} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on level2-6 ${var##*/}
    fi
    rm ${pwdout}/level2-6/${var##*/}
done

for file in ${pwdin}/hidden_functional/*.sy
do
    var=${file%.*}
    bin/SysYc $file -llvm -o ${pwdout}/hidden_functional/${var##*/}.ll -O1
    clang ${pwdout}/hidden_functional/${var##*/}.ll -c -o ${pwdout}/hidden_functional/${var##*/}.o -w
    clang -static ${pwdout}/hidden_functional/${var##*/}.o lib/libsysy_x86.a
    rm -rf ${pwdout}/hidden_functional/${var##*/}.o
    mv a.out ${pwdout}/hidden_functional/${var##*/}
    if [ -f "${pwdin}/hidden_functional/${var##*/}.in" ];then
        timeout 10 ./${pwdout}/hidden_functional/${var##*/} < ${pwdin}/hidden_functional/${var##*/}.in > ./${pwdout}/hidden_functional/${var##*/}.out
        echo $? >> ${pwdout}/hidden_functional/${var##*/}.out
    else
        timeout 10 ./${pwdout}/hidden_functional/${var##*/} > ./${pwdout}/hidden_functional/${var##*/}.out
        echo $? >> ${pwdout}/hidden_functional/${var##*/}.out
    fi
    diff --strip-trailing-cr ${pwdin}/hidden_functional/${var##*/}.out ${pwdout}/hidden_functional/${var##*/}.out > /dev/null
    if [ $? == 0 ];then
        echo -e "\033[0;32;1m" Accept "\033[0;37;1m" hidden_functional ${var##*/}
        score_hidden_functional=`expr ${score_hidden_functional} + 1`
    else
        echo -e "\033[0;31;1m" Wrong answer "\033[0;37;1m" on hidden_functional ${var##*/}
    fi
    rm ${pwdout}/hidden_functional/${var##*/}
done

echo level1-1 optimize:${score1_1}/${score1_1all}
echo level1-2 optimize:${score1_2}/${score1_2all}
echo level2-1 optimize:${score2_1}/${score2_1all}
echo level2-2 optimize:${score2_2}/${score2_2all}
echo level2-3 optimize:${score2_3}/${score2_3all}
echo level2-4 optimize:${score2_4}/${score2_4all}
echo level2-5 optimize:${score2_5}/${score2_5all}
echo level2-6 optimize:${score2_6}/${score2_6all}
echo hidden_functional optimize:${score_hidden_functional}/${score_hidden_functional_all}

